language: java
sudo: false
script:  mvn clean compile install exec:java -D exec.mainClass="enso.App" "-Dbpmn=parallelTasksWithOneResource.bpmn" "-DprocessId=parallelTasksWithOneResource" "-DinstancesNumber=1" "-DdelayBetweenInstances=0"